import puppeteer from 'puppeteer'
const b=await puppeteer.launch({args:['--no-sandbox','--disable-dev-shm-usage'],headless:'new'})
const p=await b.newPage(); await p.setViewport({width:1440,height:900})
p.on('pageerror',e=>console.log('PAGEERROR:',String(e).slice(0,300)))
p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text().slice(0,300))})
await p.goto('http://localhost:5173/categories',{waitUntil:'domcontentloaded',timeout:30000})
await new Promise(r=>setTimeout(r,2000))
console.log('h2s:',await p.evaluate(()=>Array.from(document.querySelectorAll('h2')).map(h=>h.innerText.trim()).join(' | ')))
const btnInfo=await p.evaluate(()=>Array.from(document.querySelectorAll('button[aria-pressed]')).map(b=>({t:b.innerText.split('\n').filter(Boolean).slice(0,2).join(' / ')})))
console.log('buttons:',JSON.stringify(btnInfo.slice(0,3)))
await p.evaluate(()=>{Array.from(document.querySelectorAll('button[aria-pressed]')).find(b=>/Poetry/i.test(b.innerText))?.click()})
await new Promise(r=>setTimeout(r,1500))
console.log('after click h2s:',await p.evaluate(()=>Array.from(document.querySelectorAll('h2')).map(h=>h.innerText.trim()).join(' | ')))
console.log('pressed:',await p.evaluate(()=>Array.from(document.querySelectorAll('button[aria-pressed="true"]')).map(b=>b.innerText.split('\n')[1])))
const ops=await p.evaluate(()=>Array.from(document.querySelectorAll('a[aria-label^="Folio"]')).map(a=>parseFloat(getComputedStyle(a).opacity)))
console.log('plate opacities:',ops.join(','))
console.log('threads:',await p.evaluate(()=>{const hs=Array.from(document.querySelectorAll('div')).filter(d=>d.style.height==='1px'||d.getAttribute('style')?.includes('height:1px')).length;const vs=Array.from(document.querySelectorAll('div')).filter(d=>d.getAttribute('style')?.includes('width:1px')).length;return `h=${hs} v=${vs}`}))
await p.screenshot({path:'/home/user/verlyse-project/audit/shots/probe-g.png'})
await b.close()
