import puppeteer from 'puppeteer'
const b=await puppeteer.launch({args:['--no-sandbox','--disable-dev-shm-usage'],headless:'new'})
// ---- H probe ----
const p1=await b.newPage(); await p1.setViewport({width:1440,height:900})
await p1.goto('http://localhost:5173/creators',{waitUntil:'domcontentloaded',timeout:30000})
await new Promise(r=>setTimeout(r,1800))
const btns=await p1.evaluate(()=>Array.from(document.querySelectorAll('button[aria-pressed]')).map(x=>({txt:x.innerText.slice(0,30),pressed:x.getAttribute('aria-pressed')})))
console.log('H buttons:',JSON.stringify(btns.slice(0,4)))
const tgt=await p1.evaluateHandle(()=>Array.from(document.querySelectorAll('button[aria-pressed]')).find(b=>/Anshujit/i.test(b.innerText)))
console.log('H target found:',!!tgt)
await tgt.asElement().click()
await new Promise(r=>setTimeout(r,1500))
console.log('H after click activeElement:',await p1.evaluate(()=>document.activeElement?.innerText?.slice(0,20)))
console.log('H article now:',(await p1.evaluate(()=>document.querySelector('article')?.innerText||'')).slice(0,80))
console.log('H pressed buttons:',await p1.evaluate(()=>Array.from(document.querySelectorAll('button[aria-pressed="true"]')).map(x=>x.innerText.slice(0,24))))
await p1.close()
// ---- I probe ----
const p2=await b.newPage(); await p2.setViewport({width:1440,height:900})
await p2.goto('http://localhost:5173/ambassadors',{waitUntil:'domcontentloaded',timeout:30000})
await new Promise(r=>setTimeout(r,1800))
const meds=await p2.evaluate(()=>Array.from(document.querySelectorAll('button[aria-label^="№"]')).slice(0,3).map(x=>x.getAttribute('aria-label')))
console.log('I medallions:',JSON.stringify(meds))
const med=await p2.evaluateHandle(()=>document.querySelector('button[aria-label^="№"]'))
await med.asElement().click()
await new Promise(r=>setTimeout(r,1200))
console.log('I dialog exists:',await p2.evaluate(()=>!!document.querySelector('[role="dialog"]')))
console.log('I dialog text:',(await p2.evaluate(()=>document.querySelector('[role="dialog"]')?.innerText||'')).slice(0,120))
await p2.close()
await b.close()
