#!/usr/bin/env node
/**
 * sitemap.xml, generated from the canonical route registry.
 *
 * It used to be a hand-maintained file in public/. That is how it came to
 * list /creators (which had no prerendered shell) while omitting /room
 * (a real, footer-linked public page). A generated sitemap cannot drift.
 *
 * URLs carry the trailing slash the primary host actually serves, matching
 * the canonical tags emitted by prerender-metadata.mjs.
 */
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { loadRouteRegistry } from './lib/load-registry.mjs'

const dist = join(process.cwd(), 'dist')
const origin = process.env.PUBLIC_SITE_ORIGIN || undefined
const { routes, canonicalUrl } = await loadRouteRegistry(origin)

const listed = routes.filter((route) => route.sitemap)

const body = listed
  .map((route) => {
    const parts = [`<loc>${canonicalUrl(route.path)}</loc>`]
    if (route.lastmod) parts.push(`<lastmod>${route.lastmod}</lastmod>`)
    parts.push(`<changefreq>${route.changefreq}</changefreq>`)
    parts.push(`<priority>${route.priority}</priority>`)
    return `  <url>${parts.join('')}</url>`
  })
  .join('\n')

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs from src/data/routes.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`

await writeFile(join(dist, 'sitemap.xml'), xml)
console.log(`Sitemap written with ${listed.length} URLs from the route registry.`)
